/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.movimentoAcademico; 
import controller.CursosController;
import controller.MatriculaController;
import controller.MovimentoAcademicoController;
import controller.TurmaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cursos;
import model.Disciplinas;
import model.Matriculas;
import model.Alunos;
import model.MovimentosAcademicos;
import model.Turmas;
import telas.aluno.ConsultaAlunosTableModel;
import util.Formatacao;

/**
 *
 * @author Kamila
 */
public class FrmMovimentoAcademico extends javax.swing.JFrame implements IMovimentosAcademicos {
    private List<MovimentosAcademicos> listaAlunos;
    private ConsultaMovimentosAcademicosTableModel modelMovimentos;
    /**
     * Creates new form FrmConsCurso
     */
    public FrmMovimentoAcademico() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        carregarComboCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        lblNomeCurso1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCursos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        lblNomeCurso3 = new javax.swing.JLabel();
        lblNomeCurso4 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        cbxTurma = new javax.swing.JComboBox<>();
        cbxCursos = new javax.swing.JComboBox<>();

        jTextField2.setAlignmentX(0.1F);
        jTextField2.setAlignmentY(0.1F);

        lblNomeCurso1.setText("Nome da Disciplina:");
        lblNomeCurso1.setAlignmentY(0.1F);

        setTitle("Movimento Academico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaCursos.setBackground(new java.awt.Color(204, 255, 204));
        tabelaCursos.setBorder(new javax.swing.border.SoftBevelBorder(0, new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), null, null));
        tabelaCursos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Aluno", "Turma", "Disciplina", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCursos.setGridColor(new java.awt.Color(0, 102, 51));
        tabelaCursos.setSelectionBackground(new java.awt.Color(0, 102, 51));
        tabelaCursos.setSelectionForeground(new java.awt.Color(204, 255, 204));
        tabelaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCursos);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/situacao.png"))); // NOI18N
        btnExcluir.setText("Situação");
        btnExcluir.setBorder(null);
        btnExcluir.setBorderPainted(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setPreferredSize(new java.awt.Dimension(80, 90));
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblNomeCurso3.setText("Turma:");
        lblNomeCurso3.setAlignmentY(0.1F);

        lblNomeCurso4.setText("Curso:");
        lblNomeCurso4.setAlignmentY(0.1F);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar.setOpaque(false);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        cbxTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTurmaActionPerformed(evt);
            }
        });

        cbxCursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCursosItemStateChanged(evt);
            }
        });
        cbxCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeCurso4)
                            .addComponent(cbxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNomeCurso3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(14, 14, 14)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeCurso3)
                            .addComponent(lblNomeCurso4))
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCursosMouseClicked

    }//GEN-LAST:event_tabelaCursosMouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        setModel();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tabelaCursos.getSelectedRow();
        if(linha >= 0){
            new FrmSituacaoMovimentoAcademico(listaAlunos.get(linha), this);
        }else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Aluno");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbxTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTurmaActionPerformed

    private void cbxCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCursosActionPerformed

    private void cbxCursosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCursosItemStateChanged
        // TODO add your handling code here:
        Object obj = cbxCursos.getSelectedItem();
        Cursos cursos = null;
        if (obj instanceof Cursos) {
            cursos = (Cursos) obj;
        }
        if (cursos != null) {
            carregarComboTurmas(cursos);
            setModel();
        }
    }//GEN-LAST:event_cbxCursosItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxCursos;
    private javax.swing.JComboBox<String> cbxTurma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblNomeCurso1;
    private javax.swing.JLabel lblNomeCurso3;
    private javax.swing.JLabel lblNomeCurso4;
    private javax.swing.JTable tabelaCursos;
    // End of variables declaration//GEN-END:variables
    
    
    public void carregarComboTurmas(Cursos curso) {
        TurmaController turmasController = new TurmaController();
        cbxTurma.removeAllItems();
        String sql = "select t from Turmas t where t.cursosId.id = "+curso.getId();
        List<Turmas> listaTurma = turmasController.listar(sql);
        if (listaTurma != null) {
            cbxTurma = Formatacao.preencherComobox(listaTurma, cbxTurma, true, "Selecione");
        } else {
            cbxTurma.removeAllItems();
        }
    }
    
    public void carregarComboCurso() {
        CursosController cursosController = new CursosController();
        String sql = "select c from Cursos c order by c.nome";
        List<Cursos> listaCursos = cursosController.listar(sql);
        if (listaCursos != null) {
            cbxCursos = Formatacao.preencherComobox(listaCursos, cbxCursos, true, "Selecione");
        } else {
            cbxCursos.removeAllItems();
        }
    }
    @Override
    public void setModel() {
       
        Cursos curso = null;
        Object objCurso = cbxCursos.getSelectedItem();
        Turmas turma = null;
        Object objTurma = cbxTurma.getSelectedItem();
        if(objTurma instanceof Turmas){
            turma = (Turmas) objTurma;
        } 
        if(objCurso instanceof Cursos){
            curso = (Cursos) objCurso;
        } 
        MovimentoAcademicoController movimentoController = new MovimentoAcademicoController();
        if(curso == null || turma == null){
            listaAlunos = new ArrayList<MovimentosAcademicos>();
        } else {
            String sql = "select m from MovimentosAcademicos m "
                    + "where m.matriculasId.turmasId.id = "+turma.getId();

            listaAlunos = movimentoController.listar(sql);

            if (listaAlunos == null) {
                listaAlunos = new ArrayList<MovimentosAcademicos>();
            } 
        }
        modelMovimentos = new ConsultaMovimentosAcademicosTableModel(listaAlunos);
            tabelaCursos.setModel(modelMovimentos);
            tabelaCursos.getColumnModel().getColumn(0).setPreferredWidth(70);
            tabelaCursos.getColumnModel().getColumn(1).setPreferredWidth(175);
            tabelaCursos.getColumnModel().getColumn(2).setPreferredWidth(175);
            tabelaCursos.getColumnModel().getColumn(3).setPreferredWidth(175);
            tabelaCursos.repaint();
    }
}

